module.exports = require('yargs')
  .usage('Usage: $0 --url [url]')
  .demand('u')
  .alias('u', 'url')
  .describe('u', 'Application URL (eg. http://example.com)')
  .alias('p', 'port')
  .describe('p', 'Port number for the Express application')
  .default('p', 3000)
  .describe('redis-host', 'Redis Server hostname')
  .default('redis-host', 'localhost')
  .describe('redis-port', 'Redis Server port number')
  .default('redis-port', 6379)
  .describe('redis-pass', 'Redis Server password')
  .default('redis-pass', false)
  .argv;
